#!/bin/bash

ISPARU=/sbin/paru
if [ -f "$ISPARU" ]; then 
    echo -e "paru was located, moving on.\n"
    paru -Suy
else 
    echo -e "paru was not located, please install paru. Exiting script.\n"
    exit 
fi

### Disable wifi powersave mode ###
read -n1 -rep 'Would you like to disable wifi powersave? (y,n)' WIFI
if [[ $WIFI == "Y" || $WIFI == "y" ]]; then
    LOC="/etc/NetworkManager/conf.d/wifi-powersave.conf"
    echo -e "The following has been added to $LOC.\n"
    echo -e "[connection]\nwifi.powersave = 2" | sudo tee -a $LOC
    echo -e "\n"
    echo -e "Restarting NetworkManager service...\n"
    sudo systemctl restart NetworkManager
    sleep 3
fi

### Install all of the above pacakges ####
read -n1 -rep 'Would you like to install the packages? (y,n)' INST
if [[ $INST == "Y" || $INST == "y" ]]; then
    paru -S --noconfirm kitty thunar ranger htop ntfs-3g \
    ttf-jetbrains-mono-nerd noto-fonts-emoji starship \
		ttf-material-design-icons-desktop-git ttf-iosevka-nerd \
    brightnessctl firefox os-prober shell-color-scripts  \
		dmenu lsd ripgrep bat fzf picom rofi-wayland neofetch \
		hyprland waybar dunst pipewire wireplumber qt5-wayland qt6-wayland \
		polkit-kde-agent hyprpaper hyprpicker xdg-desktop-portal-hyprland \
		hypridle hyprlock cliphist network-manager-applet overskride udiskie

    # Start the bluetooth service
    # echo -e "Starting the Bluetooth Service...\n"
    # sudo systemctl enable --now bluetooth.service
    # sleep 2
fi
