terminal = "kitty"
browser = "google-chrome-stable"
terminal_explorer = terminal + " -e ranger"
file_explorer = "thunar"
apps_menu = "rofi -modi drun -show drun"
screenshot = "deepin-screenshot"
music_player = terminal + " -e mocp"
