# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix
{
  pkgs,
  fetchurl,
  fetchgit,
  fetchhg,
}: self: super: {
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "25.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/77/06/bb80f5f86020c4551da315d78b3ab75e8228f89f0162f2c3a819e407941a/attrs-25.3.0-py3-none-any.whl";
      sha256 = "1hrv1vjc46jqmnb1bxn6zybrm283dw910d3q82jzw08p0g71hws2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cattrs" = super.buildPythonPackage rec {
    pname = "cattrs";
    version = "24.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3c/ee/d68a3de23867a9156bab7e0a22fb9a0305067ee639032a22982cf7f725e7/cattrs-24.1.3-py3-none-any.whl";
      sha256 = "1xc3i8fi7n0vxwjhab3wbcn1kcnk9mn0l1mxzwkhz116vpfmgydd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."exceptiongroup"
      self."typing-extensions"
    ];
  };
  "constructs" = super.buildPythonPackage rec {
    pname = "constructs";
    version = "10.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f2/d9/c5e7458f323bf063a9a54200742f2494e2ce3c7c6873e0ff80f88033c75f/constructs-10.4.2-py3-none-any.whl";
      sha256 = "1h8kbxj62k4haiwrn4s8g3si2in3p2c0cd16z3hgvszd0jq5j3qz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jsii"
      self."publication"
      self."typeguard"
    ];
  };
  "exceptiongroup" = super.buildPythonPackage rec {
    pname = "exceptiongroup";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/f4/c6e662dade71f56cd2f3735141b265c3c79293c109549c1e6933b0651ffc/exceptiongroup-1.3.0-py3-none-any.whl";
      sha256 = "044alxyhkfdlr5z3xlpnf5lv78310bnsgnkdmm669l0k1ip1w4ad";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "importlib-resources" = super.buildPythonPackage rec {
    pname = "importlib-resources";
    version = "6.5.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a4/ed/1f1afb2e9e7f38a545d628f864d562a5ae64fe6f7a10e28ffb9b185b4e89/importlib_resources-6.5.2-py3-none-any.whl";
      sha256 = "1v6cc2kxi319k1d0k77psninkv8wflk83jval1kqpir8xp1zv73q";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
  };
  "jsii" = super.buildPythonPackage rec {
    pname = "jsii";
    version = "1.112.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/44/af/8554b632e2b82f37a7422782aba5db2a1fbff4887faa7ec850818def8407/jsii-1.112.0-py3-none-any.whl";
      sha256 = "18amkzm0r1vkvql89rpzyzzyrng4j6klj22ps1pj16sd0wiw4435";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."cattrs"
      self."importlib-resources"
      self."publication"
      self."python-dateutil"
      self."typeguard"
      self."typing-extensions"
    ];
  };
  "publication" = super.buildPythonPackage rec {
    pname = "publication";
    version = "0.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f8/d3/6308debad7afcdb3ea5f50b4b3d852f41eb566a311fbcb4da23755a28155/publication-0.0.3-py2.py3-none-any.whl";
      sha256 = "1rpv7asi5kbyw6qnvjf0x3rvrnmj7a75r389l7c13g7ya59qhj02";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.9.0.post0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateutil-2.9.0.post0-py2.py3-none-any.whl";
      sha256 = "09q48zvsbagfa3w87zkd2c5xl54wmb9rf2hlr20j4a5fzxxvrcm8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.17.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/ce/149a00dd41f10bc29e5921b496af8b574d8413afcd5e30dfa0ed46c2cc5e/six-1.17.0-py2.py3-none-any.whl";
      sha256 = "0x1jdic712dylbnyiqdj4xyxrlx0gaacynmbmkfiym4hxn8z68a7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typeguard" = super.buildPythonPackage rec {
    pname = "typeguard";
    version = "2.13.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9a/bb/d43e5c75054e53efce310e79d63df0ac3f25e34c926be5dffb7d283fb2a8/typeguard-2.13.3-py3-none-any.whl";
      sha256 = "1wc4cahvzahjfc4i409s9slsljf86qgkvxjsmsppwzl83vh3ngjy";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.14.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b5/00/d631e67a838026495268c2f6884f3711a15a9a2a96cd244fdaea53b823fb/typing_extensions-4.14.1-py3-none-any.whl";
      sha256 = "0xhxfdahfwdkvr7nlxmlq8v4m94flhh29nkf3l1r7p3lhfsy7qfi";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "3.23.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2e/54/647ade08bf0db230bfea292f893923872fd20be6ac6f53b2b936ba839d75/zipp-3.23.0-py3-none-any.whl";
      sha256 = "0kmishxksv9559qyklb08s46mzddq0vc6d0xrvsk5m2y27b545h7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
